/* 
	DDL - Criar schema e tabelas ( Create, Alter e Drop)
	DML - Instruções de Insert, Update e Delete
	DQL - Select
*/

-- DDL - CLINICA

CREATE SCHEMA CLINICA IF NOT EXISTS;

SET SEARCH_PATH TO CLINICA;

CREATE TABLE CLINICA.MEDICO (
		ID_MEDICO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		NOME TEXT NOT NULL,
		CRM TEXT NOT NULL,
		ESPECIALIDADE TEXT NOT NULL
);

SELECT * FROM CLINICA.PACIENTE

CREATE TABLE CLINICA.CLINICA (
		ID_CLINICA INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		NOME TEXT NOT NULL,
		DESCRICAO TEXT NOT NULL,
		ENDERECO TEXT NOT NULL
);


CREATE TABLE CLINICA.PACIENTE (
		ID_PACIENTE INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		CPF VARCHAR(11),
		NOME TEXT NOT NULL,
		IDADE INT NOT NULL,
		DAT_NASC DATE NOT NULL
);

--ALTERAR A TABELA PARA INCLUIR UM CAMPO UNICO
ALTER TABLE CLINICA.PACIENTE
		ADD CONSTRAINT UNQCPF UNIQUE (CPF);

CREATE TABLE CLINICA.CONSULTA(
		ID_CONSULTA INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		ID_PACIENTE INT NOT NULL,
		ID_MEDICO INT NOT NULL,
		ID_CLINICA INT NOT NULL,
		DATA_CONSULTA TIMESTAMP WITH TIME ZONE NOT NULL,
		VALOR_CONSULTA NUMERIC(8,2) NOT NULL,
		FOREIGN KEY (ID_PACIENTE) REFERENCES CLINICA.PACIENTE (ID_PACIENTE),
		FOREIGN KEY (ID_MEDICO) REFERENCES CLINICA.MEDICO (ID_MEDICO),
		FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA.CLINICA (ID_CLINICA)
);




/* CREATE TABLE CLINICA.MEDICO2 AS SELECT * FROM CLINICA.MEDICO;
