
CREATE SCHEMA ECOMMERCE;

CREATE TABLE ECOMMERCE.CLIENTE (
		CLIENTE_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		NOME_COMPLETO TEXT NOT NULL,
		EMAIL TEXT NOT NULL,
		SENHA TEXT NOT NULL,
		TELEFONE TEXT NULL,
		DATA_CADASTRO TIMESTAMPTZ NOT NULL
);


CREATE TABLE ECOMMERCE.ENDERECO_DE_ENTREGA(
		ENDERECO_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		CLIENTE_ID INT NOT NULL,
		LOGRADOURO TEXT NOT NULL,
		NUMERO VARCHAR(10) NOT NULL,
		COMPLEMENTO TEXT NULL,
		BAIRRO TEXT NOT NULL,
		CIDADE TEXT NOT NULL,
		ESTADO CHAR(2) NOT NULL,
		CEP TEXT NOT NULL,
		FOREIGN KEY (CLIENTE_ID) REFERENCES ECOMMERCE.CLIENTE (CLIENTE_ID)
);

CREATE TABLE ECOMMERCE.PEDIDO (
		PEDIDO_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		CLIENTE_ID INT NOT NULL,
		ENDERECO_ID INT NOT NULL,
		DATA_PEDIDO TIMESTAMPTZ NOT NULL,
		VALOR_TOTAL NUMERIC(13,2) NOT NULL,
		STATUS TEXT NOT NULL,
		FOREIGN KEY (CLIENTE_ID) REFERENCES ECOMMERCE.CLIENTE (CLIENTE_ID),
		FOREIGN KEY (ENDERECO_ID) REFERENCES ECOMMERCE.ENDERECO_DE_ENTREGA (ENDERECO_ID)
);

CREATE TABLE ECOMMERCE.PAGAMENTO (
		PAGAMENTO_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		PEDIDO_ID INT NOT NULL,
		FORMA_PAGAMENTO TEXT NOT NULL,
		STATUS TEXT NOT NULL,
		DATA_PAGAMENTO TIMESTAMPTZ NOT NULL,
		FOREIGN KEY (PEDIDO_ID) REFERENCES ECOMMERCE.PEDIDO(PEDIDO_ID)
);


CREATE TABLE ECOMMERCE.CATEGORIA(
		CATEGORIA_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		NOME_CATEGORIA TEXT NOT NULL,
		DESCRICAO TEXT NULL
);

CREATE TABLE ECOMMERCE.PRODUTO(
		PRODUTO_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		CATEGORIA_ID INT NOT NULL REFERENCES ECOMMERCE.CATEGORIA(CATEGORIA_ID),
		NOME_PRODUTO TEXT NOT NULL,
		DESCRICAO TEXT NULL,
		PRECO NUMERIC(13,2) NOT NULL,
		ESTOQUE_DISPONIVEL INT NOT NULL,
		IMAGEM_URL TEXT NULL
);

CREATE TABLE ECOMMERCE.ITEM_DO_PEDIDO(
		ITEM_ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		PEDIDO_ID INT NOT NULL REFERENCES ECOMMERCE.PEDIDO(PEDIDO_ID),
		PRODUTO_ID INT NOT NULL REFERENCES ECOMMERCE.PRODUTO(PRODUTO_ID),
		QUANTIDADE INT NOT NULL
);

